config/routes.rb
Grabbit3::Application.routes.draw do

  resources :download_jobs do
    post 'search', :on => :collection
  end

  resources :subscriptions do
    resources :download_jobs
  end
  
  resources :resources
  
  resources :tags
  
  match 'download_jobs/tagged/:tag_name/' => 'download_jobs#index'
  match 'subscriptions/tagged/:tag_name/' => 'subscriptions#index'
  
  match 'download_jobs/tagged/:tag_name/feed' => 'download_jobs#feed'

  # OmniAuth login routes
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get   '/logout', :to => 'sessions#destroy'
  
  get "home/index"

  root :to => 'home#index'
end

app/models/subscription.rb
require 'tag_holder'
require 'resource_holder'

class XMLTag  
  def initialize(description, value)
    @description = description
    @value = value
  end
  
  def description
    @description
  end
  
  def value
    @value
  end
  
  All = [
      new("Use the file included in each feed item", "enclosure"),
      new("Use the URL each item points to", "link")
  ]
end

class Subscription < ActiveRecord::Base
  belongs_to :resource
  belongs_to :user
  has_many :download_jobs
  has_and_belongs_to_many :tags
  
  include TagHolder
  extend TagHolder::ClassMethods
  include ResourceHolder
end

app/controllers/subscriptions_controller.rb
require 'user_holder_controller'

class SubscriptionsController < ApplicationController
  include UserHolderController

  # GET /subscriptions
  # GET /subscriptions.json
  
  before_filter :login_required, :except => [:show, :index]
  
  def login_required
    redirect_to(subscriptions_url, :notice => "You'll need to log in for that.") unless session[:user_id]
  end
  
  def index
    user_ids = [nil]
    user_ids << @user.id if @user
    @subscriptions = Subscription.where(:user_id => user_ids) 
    
    if params[:tag_name]
      @tag = Tag.find_by_name params[:tag_name]
      @subscriptions = Subscription.find_by_tag(@tag.name)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @subscriptions }
      format.opml # index.opml.erb
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])
    
    redirect_to subscriptions_url, :notice => "Sorry. You can't see that one." unless @user == @subscription.user or @subscription.user == nil

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new  
    @subscription = Subscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(params[:subscription])

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, :notice => 'Subscription was successfully created.' }
        format.json { render :json => @subscription, :status => :created, :location => @subscription }
      else
        format.html { render :action => "new" }
        format.json { render :json => @subscription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])
    
    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to @subscription, :notice => 'Subscription was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @subscription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :destination %>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :extension %>
    <%= f.text_field :extension %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names %>
  </div>
  <div class="field radio">
    <% XMLTag::All.each do |tag| %>
      <%= radio_button_tag 'subscription[url_element]', tag.value, @subscription.url_element == tag.value %> <label for="subscription_url_element_<%= tag.value %>"><%= tag.description %></label><br />
    <% end %>
  </div>
  <div class="field radio">
    <%= radio_button_tag 'subscription[user_id]', @user.id, @subscription.user == @user %>
    <label for="subscription_user_id_<%= @user.id %>">Only I can see this subscription</label>
    <br />
    <%= radio_button_tag 'subscription[user_id]', '', @subscription.user != @user %>
    <label for="subscription_user_id_">Anyone can see this subscription</label>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>
<hr />

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<%
  title = "Subscriptions"
  
  if @tag
    if @tag.title
      title += " for <em>#{@tag.title}</em>"
    else
      title += " tagged <em>#{@tag.name}</em>"
    end
  end
%>
<h1><%= title.html_safe %></h1>
<hr/>
<p id="notice"><%= notice %></p>

<p><%= link_to 'New Subscription', new_subscription_path, :class => 'btn' if @user %></p>

<table>
  <tr class="subscription row">
    <th class="span6">Title</th>
    <th class="span1">Items</th>
    <%- if @user %>
    <th class="span3" colspan=2></th>
    <%- end %>
  </tr>
  <% @subscriptions.each do |subscription| %>
    <tr class="subscription row">
      <td class="span6"><%= link_to subscription.title, subscription.url %></td>
      <td class="span1"><%= link_to subscription.download_jobs.count, url_for(subscription) %></td>
      <%- if @user %>
        <td class="span1"><%= link_to 'Edit', edit_subscription_path(subscription), :class => 'btn btn-primary btn-mini' %></td>
        <td class="span2"><%= link_to 'Unsubscribe', subscription, :method => :delete , :class => 'btn btn-mini', :confirm => 'Are you sure?' %></td>
      <%- end %>
    </tr>
  <% end %>
</table>

app/views/subscriptions/index.opml.erb
<?xml version="1.0" encoding="ISO-8859-1"?>
<opml version="2.0">
  <head>
    <title>Grabbit subscriptions<%= " tagged '#{ @tag }'" unless @tag.blank? %></title>
    <dateCreated><%= @subscriptions.first.created_at.to_s(:rfc5322) %></dateCreated>
    <dateModified><%= @subscriptions.last.updated_at.to_s(:rfc5322) %></dateModified>
    <ownerName>Lucas Wilson-Richter</ownerName>
    <ownerEmail>grabbit@lucasrichter.id.au</ownerEmail>
  </head>
  <body>
  <% @subscriptions.each do |subscription| %>
    <outline text="<%= subscription.title %>" title="<%= subscription.title %>" type="rss" xmlUrl="<%= subscription.url %>"/>
  <% end %>
  </body>
</opml>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @subscription.title %></h1>
<hr />

<p>
  <b>Destination:</b>
  <%= @subscription.destination.blank? ? "<em>None</em>".html_safe : @subscription.destination %>
</p>

<p>
  <b>Extension:</b>
  <%= @subscription.extension.present? ? '.' + @subscription.extension : "<em>None</em>".html_safe %>
</p>

<p>
  <b>URL:</b>
  <a href="<%= @subscription.url %>"><%= @subscription.url %></a>
</p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>