config/routes.rb
Grabbit3::Application.routes.draw do

  resources :download_jobs do
    post 'search', :on => :collection
  end

  resources :subscriptions do
    resources :download_jobs
  end
  
  resources :resources
  
  resources :tags
  
  match 'download_jobs/tagged/:tag_name/' => 'download_jobs#index'
  match 'subscriptions/tagged/:tag_name/' => 'subscriptions#index'
  
  match 'download_jobs/tagged/:tag_name/feed' => 'download_jobs#feed'

  # OmniAuth login routes
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get   '/logout', :to => 'sessions#destroy'
  
  get "home/index"

  root :to => 'home#index'
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.title %></td>
    <td><%= resource.url %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @resource.title %>
</p>

<p>
  <b>Url:</b>
  <%= @resource.url %>
</p>

<p>
  <b>Status:</b>
  <%= @resource.status %>
</p>

<p>
  <b>Directory:</b>
  <%= @resource.directory %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>