config/routes.rb
Grabbit3::Application.routes.draw do

  resources :download_jobs do
    post 'search', :on => :collection
  end

  resources :subscriptions do
    resources :download_jobs
  end
  
  resources :resources
  
  resources :tags
  
  match 'download_jobs/tagged/:tag_name/' => 'download_jobs#index'
  match 'subscriptions/tagged/:tag_name/' => 'subscriptions#index'
  
  match 'download_jobs/tagged/:tag_name/feed' => 'download_jobs#feed'

  # OmniAuth login routes
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get   '/logout', :to => 'sessions#destroy'
  
  get "home/index"

  root :to => 'home#index'
end

app/models/download_job.rb
require 'tag_holder'

Status = {
    :not_started => "Not Started",
    :in_progress => "In Progress",
    :finished => "Finished",
    :failed => "Failed",
    :retry => "Retry",
    :cancelled => "Cancelled"
}

class DownloadJobValidator < ActiveModel::Validator
  # Maximum length of a URL, as defined in the DB.
  UrlMaxLength = 1023

  def validate(record)
    record.errors[:base] << "This item is a duplicate." if pending_download_exists(record)
  end
  
  def pending_download_exists(record)
    search_url = record.url.length > UrlMaxLength ? record.url[0..UrlMaxLength-1] : record.url
  
    jobs = DownloadJob.where(:url => search_url, :subscription_id => record.subscription.try(:id))
    
    job_count = jobs.where(:status => [Status[:not_started], Status[:in_progress], Status[:retry]]).length
    job_count += jobs.where(["status in (?) and updated_at > ?", [Status[:finished], Status[:failed], Status[:cancelled]], 6.months.ago]).length
    
    job_count > 0
  end
end

class DownloadJob < ActiveRecord::Base
  belongs_to :subscription
  belongs_to :user
  has_and_belongs_to_many :tags

  include TagHolder
  extend TagHolder::ClassMethods
  
  validates_with DownloadJobValidator, :on => :create
  
  before_validation :set_initial_attributes, :on => :create
  after_create :adopt_tags_from_subscription
  
  self.per_page = 30
  
  def set_initial_attributes
    self.status = Status[:not_started]
  end

  def adopt_tags_from_subscription
    if self.subscription
      add_tags self.subscription.tags 
      self.save
    end
  end

  def extension
    self.subscription.extension if self.subscription
  end
  
  def destination
    self.subscription.destination if self.subscription
  end
end

app/controllers/download_jobs_controller.rb
require 'feed_fetcher'
require 'user_holder_controller'
require 'net/http'

class DownloadJobsController < ApplicationController
  include UserHolderController

  protect_from_forgery :only => [ :delete ]

  before_filter :default_format_json, :only => :feed
  before_filter :login_required, :except => [:index, :show, :feed, :search] unless ENV['GRABBIT_INSECURE'] == '1'
  
  def login_required
    redirect_to(download_jobs_url, :notice => "You'll need to log in for that.") unless session[:user_id]
  end

  def default_format_json
    request.format = "json" unless params[:format]
  end

  # GET /download_jobs
  # GET /download_jobs.json
  def index
    djs = nil
    conditions = { :user_id => [nil, (@user ? @user.id : nil)] }
    order = 'download_jobs.id desc'
  
    if params[:tag_name]
      @tag = Tag.find_by_name(params[:tag_name])
      djs = @tag.download_jobs
    elsif params[:subscription_id]
      djs = Subscription.find(params[:subscription_id]).download_jobs
    end
    
    @download_jobs = (djs || DownloadJob).where(conditions).paginate(:page => params[:page]).order(order)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @download_jobs }
    end
  end
  
  # There should always be only one tag in params[].
  def feed
    @tag_name = params[:tag_name]
    @tag = Tag.find_by_name(@tag_name)

    if @tag.nil?
      @download_jobs = []
    else
      @download_jobs = @tag.download_jobs \
        .where(:status => [Status[:not_started], Status[:retry]], :user_id => [nil, (@user ? @user.id : nil)]) \
        .order('download_jobs.id desc') \
        .paginate(:page => params[:page])
    end
    
    @feed_updated_at = @download_jobs.first.updated_at || @download_jobs.first.created_at unless @download_jobs.empty?
    @feed_updated_at = Time.now unless @feed_updated_at
    
    @feed_title = (@tag.nil? || @tag.title.blank?) ? "Grabbit feed for \"#{ params[:tag_name]}\"" : @tag.title
    
    respond_to do |format|
      format.json { render :json => @download_jobs }
      format.rss { render :layout => false }
    end
  end
  
  # GET /download_jobs/1
  # GET /download_jobs/1.json
  def show
    @download_job = DownloadJob.find(params[:id])
    
    redirect_to download_jobs_url, :notice => "Sorry, you can't see that one." if @download_job.user and @download_job.user != @user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @download_job }
    end
  end

  # GET /download_jobs/new
  # GET /download_jobs/new.json
  def new
    @download_job = DownloadJob.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @download_job }
    end
  end

  # GET /download_jobs/1/edit
  def edit
    @download_job = DownloadJob.find(params[:id])
  end

  # POST /download_jobs
  # POST /download_jobs.json
  def create
    @download_job = DownloadJob.new(params[:download_job])

    respond_to do |format|
      if @download_job.save
        format.html { redirect_to @download_job, :notice => 'Download job was successfully created.' }
        format.json { render :json => @download_job, :status => :created, :location => @download_job }
      else
        format.html { render :action => "new" }
        format.json { render :json => @download_job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /download_jobs/1
  # PUT /download_jobs/1.json
  def update
    @download_job = DownloadJob.find(params[:id])

    respond_to do |format|
      if @download_job.update_attributes(params[:download_job])
        format.html { redirect_to @download_job, :notice => 'Download job was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @download_job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /download_jobs/1
  # DELETE /download_jobs/1.json
  def destroy
    @download_job = DownloadJob.find(params[:id])
    @download_job.destroy

    respond_to do |format|
      format.html { redirect_to download_jobs_url }
      format.json { head :ok }
    end
  end
  
  def search
    user_ids = [nil]
    user_ids << @user.id if @user
    @download_jobs = DownloadJob.where(:url => params[:url], :user_id => user_ids).order('download_jobs.id desc').limit(10)
    
    render :json => @download_jobs
  end
end

app/helpers/download_jobs_helper.rb
module DownloadJobsHelper
end

app/views/download_jobs/_form.html.erb
<%= form_for(@download_job) do |f| %>
  <% if @download_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@download_job.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @download_job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :directory %>
    <%= f.text_field :directory %>
  </div>
  <div class="field">
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names %>
  </div>
  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, Status.values %>
  </div>
  <div class="field radio">
    <%= radio_button_tag 'download_job[user_id]', @user.id, @download_job.user == @user %>
    <label for="download_job_user_id_<%= @user.id %>">Only I can see this item</label>
    <br />
    <%= radio_button_tag 'download_job[user_id]', '', @download_job.user != @user %>
    <label for="download_job_user_id_">Anyone can see this item</label>
  </div>
  <div class="actions">
    <%= f.submit "Update item", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/download_jobs/edit.html.erb
<h1>Editing item</h1>
<hr />

<%= render 'form' %>

<%= link_to 'Show', @download_job %> |
<%= link_to 'Back', download_jobs_path %>

app/views/download_jobs/feed.rss.erb
<?xml version="1.0"?>
<rss version="2.0">
  <channel>
    <title><%= h @feed_title %></title>
    <link><%= root_url.chomp('/') + download_jobs_path %>/tagged/<%= @tag_name %>/feed.rss</link>
    <description>A list of items tagged "<%= h @tag_name %>", from the Grabbit RSS feed combiner.</description>
    <language>en-us</language>
    <pubDate><%= @feed_updated_at.to_formatted_s(:rfc822) %></pubDate>
    <docs>http://cyber.law.harvard.edu/rss/rss.html</docs>
    <generator>Grabbit v3</generator>
    <% @download_jobs.each do |dj| %>
    <item>
      <title><%= h dj.title %></title>
      <link><%= dj.url %></link>
      <guid isPermaLink="true"><%= root_url.chomp('/') + download_job_path(dj.id) %></guid>
      <pubDate><%= dj.updated_at.to_formatted_s(:rfc822) %></pubDate>
      <% dj.tags.each do |tag| %>
      <category><%= h tag.name %></category>
      <% end %>
      <% if @tag.show_source && dj.subscription %>
      <source url="<%= dj.subscription.url %>"><%= dj.subscription.title %></source>
      <% end %>
    </item>
    <% end %>
  </channel>
</rss>

app/views/download_jobs/index.html.erb
<% 
  title = "Items" 
  if @tag
    if @tag.title
      title = @tag.title 
    else
      title += " tagged <em>#{@tag.name}</em>"
    end
  end
%>
<h1><%= title.html_safe %></h1>
<hr />
<% @download_jobs.each do |download_job| %>
  <div class="row">
    <span class="span6"><%= link_to download_job.title, download_job.url %></span>
    <span class="span2"><%= download_job.status %></span>
    <%- if @user %>
      <span class="span1"><%= link_to 'Edit', edit_download_job_path(download_job), :class => 'btn btn-mini btn-primary' %></span>
      <span class="span1"><%= link_to 'Destroy', download_job, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini' %></span>
    <%- end %>
  </div>
<% end %>
<%= will_paginate @download_jobs, :renderer => BootstrapPagination::Rails %>

app/views/download_jobs/new.html.erb
<h1>New item</h1>
<hr />

<%= render 'form' %>

<%= link_to 'Back', download_jobs_path %>

app/views/download_jobs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @download_job.title %></h1>
<hr />

<h2><%= @download_job.status %></h2>

<p>
  <a href="<%= @download_job.url %>"><%= @download_job.url %></a>
</p>

<p>
  <em>Tagged:</em>
  <%= @download_job.tag_names %>
</p>

<%= link_to 'Edit', edit_download_job_path(@download_job) %> |
<%= link_to 'Back', download_jobs_path %>